# -*- coding: utf-8 -*-
"""find-factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmCyD4bExnzVBDV736KoUz9uq0tHQrAU
"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Calculate the factorial of 5
result = factorial(5)
print("Factorial of 5:", result)